# build config
markdown: rdiscount 

# change these
title: 3 Boys Photography
desc: 3 Boys Photography
tags: Gettysburg, Gettysburg PA, Adams County, PA, Photography, Portraits, Portrait Photography, Portrait Photographer, Children's Photography, Children's Photographer, Family Photography, Family Photographer
email: Email: james@3boysphotography.com
phone: Call: 717-357-7614
