# build config
markdown: rdiscount 

# change these
title: 3 Boys Photography
desc: 3 Boys Photography
tags: Gettysburg, Gettysburg PA, Adams County, Photography, Portraits, Portrait Photography, Portrait Photographer, Children's Photography, Children's Photographer, Family Photography, Family Photographer
email: james@3boysphotography.com
phone: 717.357.7614
